---
title: "derek_questions_june_15"
author: "Don Radcliffe"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message = FALSE, include = FALSE}
require(here)
require(dplyr)
require(tidyr)
require(ggplot2)

import_dir_cnf <- here::here('data', 'colville')
import_dir_ma <- here::here('data')
```

## Colville
```{r read and format colville data, message = FALSE}
## Colville Data
raw_cnf_trees <- read.csv(file.path(import_dir_cnf, 'trees_tidy.csv'))
cnf_plot_info <- read.csv(file.path(import_dir_cnf, 'plot_info.csv'))

cnf_trees <- raw_cnf_trees %>%
  full_join(cnf_plot_info, by = c('plot')) %>%
  ## Filter dead tree data out of my portion, not sure if Clark & Loehman included it.
  filter(status != 'dead')
```

## Metaanlysis
```{r read and format metaanlysis data, message = FALSE}
raw_ma <- read.csv(file.path(import_dir_ma, 'web_plot_digitizer_data.csv'))
factored_ma <- raw_ma %>%
  filter(treatment != 'wildfire_low') %>%
  mutate(treatment = factor(treatment, 
         levels = c('control', 'burn', 'thin', 'thinburn',
                    'control+beetle', 'burn+beetle', 'thin+beetle', 'thinburn+beetle',
                    'undifferentiated')))
```

Some graphing standardization:
```{r graphing code}
## Theme for graphing.
simpletheme <- theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.line = element_line(size = 0.2, color = 'black')) +
  theme(legend.key=element_blank(), legend.background=element_blank())

treatment_colors <- c('control' = 'deepskyblue1',
                      'burn' = 'red3', 
                      'thin' = 'gold2',
                      'thinburn' = 'purple3',
                      'control+beetle' = 'gray70',
                      'burn+beetle' = 'gray55',
                      'thin+beetle' = 'gray40',
                      'thinburn+beetle' = 'gray25',
                      'undifferentiated' = 'saddlebrown')
```

