---
title: "longevity_meta_graphs"
author: "Don Radcliffe"
date: "6/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read data, load packages, message = FALSE}
require(here)
require(dplyr)
require(tidyr)
require(ggplot2)
require(stringr)

import_dir_ma <- here::here('data')
export_dir_ma <- here::here('graphs')

raw <- read.csv(file.path(import_dir_ma, 'web_plot_digitizer_data.csv'))
factored <- raw %>%
  ## Because I labelled NPS data with an underscore.
  mutate(treatment = str_replace_all(treatment, 'thin_burn', 'thinburn')) %>%
  ## Noonan-Wright is a subset of Vaillant
  filter(study != 'noonan-wright') %>%
  ## We decided we're only going with four treatments
  filter(treatment == 'control' | treatment == 'burn' | treatment == 'thin' | treatment == 'thinburn') %>%
   mutate(treatment = str_to_title(treatment)) %>%
  mutate(treatment = factor(treatment, 
         levels = c('Control', 'Burn', 'Thin', 'Thinburn'))) %>%
  mutate(forest_type = factor(forest_type, levels = c(
    'Ponderosa Pine', 'Mixed Conifer', 'Both'))) %>%
  mutate(region = case_when(
    region == 'washington' ~ 'Washington',
    region == 'sierra_nevada' ~ 'Sierra Nevada',
    TRUE ~ 'Other')) %>%
  mutate(region = factor(region, levels = c('Washington', 'Sierra Nevada', 'Other'))) %>%
  ## Get years_post to the other side of 0.
  mutate(years_post = case_when(
    years_post == 0 & study != 'radcliffe3' ~ -1,
    years_post == 0 & study == 'radcliffe3' ~ 0.5,
    TRUE ~ years_post))
```

Some graphing standardization:
```{r graphing code}
## Theme for graphing.
simpletheme <- theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.line = element_line(size = 0.2, color = 'black')) +
  theme(legend.key=element_blank(), legend.background=element_blank())

treatment_colors <- c('control' = 'deepskyblue1',
                      'burn' = 'red3', 
                      'thin' = 'gold2',
                      'thinburn' = 'purple3',
                      'control+beetle' = 'gray70',
                      'burn+beetle' = 'gray55',
                      'thin+beetle' = 'gray40',
                      'thinburn+beetle' = 'gray25',
                      'undifferentiated' = 'saddlebrown')

region_colors <- c('Washington' = 'purple3',
                   'Sierra Nevada' = 'red2',
                   'Other' = 'gold3')

## Graphing function with all the repetitive components.
gg_fun <- function(table, variable) {
  yvar = enquo(variable)
  ggplot(table, aes(x = years_post, y = !!yvar)) +
    geom_jitter(aes(color = region, shape = forest_type), size = 3.5, alpha = 0.5) +
    facet_wrap(vars(treatment)) +
    scale_color_manual(values = region_colors, name = 'Region') +
    scale_shape_discrete(name = 'Forest Type') +
    coord_cartesian(xlim = c(-0.5, 23)) +
    expand_limits(y = 0) +
    scale_x_continuous(expand = expansion(mult = c(.1, .04))) +
    xlab('Years after treatment') +
    geom_abline(intercept = 0, slope = 10000000000, lty = 'dotted') +
    theme_bw() +
    theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank())
}

## ggsave function for consistent formatting
save_graph <- function(graph, name) {
    ggsave(plot = graph, device = 'png', filename = file.path(export_dir_ma, paste0(name,'.png')), 
    height = 4, width = 8, units = 'in', dpi = 300)
}
```

We're going to take this variable by variable since there are different issues with lumping and units for each variable. 

```{r fwd}
fwd_table <- factored %>%
  filter(variable == 'fwd' | variable == 'one_hour' | 
         variable == 'ten_hour' | variable == 'hundred_hour') %>%
  ## Un♥it conversion to Megagrams per hectare.
  mutate(value = 
           case_when(units == 'kg/m2' ~ 10 * value,
                     units == 'Mg/ha' ~ 1 * value)) %>%
  mutate(units = 'Mg/ha') %>%
  ## Aggregating everything to FWD.
  pivot_wider(names_from = variable, values_from = value, 
              id_cols = c(study, treatment, years_post, forest_type, region, 
                          burn_season, thin_type, other)) %>%
  mutate(fwd = case_when(is.na(fwd) ~ one_hour + ten_hour + hundred_hour,
                         !is.na(fwd) ~ 1 * fwd))

gg_fwd <- gg_fun(table = fwd_table, variable = fwd) +
  ggtitle('Surface twigs (1 - 100 hour fuels)') +
  ylab('Megagrams per hectare')
gg_fwd

#save_graph(graph = gg_fwd, name = 'fwd')
```

```{r cwd}
cwd_table <- factored %>%
  ## Mission creek numbers are unreasonable
  filter(study != 'radcliffe1') %>%
  mutate(variable = str_replace_all(variable, c('thousand_sound' = 'cwd_sound', 'thousand_rotten' = 'cwd_rotten'))) %>% 
  filter(variable == 'cwd' | variable == 'cwd_rotten' | variable == 'cwd_sound') %>%
  ## Unit conversion to Megagrams per hectare.
  mutate(value = 
           case_when(units == 'kg/m2' ~ 10 * value,
                     units == 'Mg/ha' ~ 1 * value)) %>%
  mutate(units = 'Mg/ha') %>%
  pivot_wider(names_from = variable, values_from = value, 
              id_cols = c(study, treatment, years_post, forest_type, region, 
                          burn_season, thin_type, other)) %>%
  ## Units to Megagrams per hectare
  mutate(value = case_when(
    is.na(cwd) ~ cwd_rotten + cwd_sound,
    !is.na(cwd) ~ cwd * 1))

gg_cwd <- gg_fun(table = cwd_table, variable = value) +
  ggtitle('Course Woody Debris') +
  ylab('Megagrams per hectare')
gg_cwd

#save_graph(graph = gg_cwd, name = 'cwd')
```

```{r litterduff}
litter_duff_table <- factored %>%
  filter(variable == 'litter' | variable == 'duff' | 
         variable == 'litterduff') %>%
  ## Unit conversion to Megagrams per hectare.
  mutate(value = 
           case_when(units == 'kg/m2' ~ 10 * value,
                     units == 'Mg/ha' ~ 1 * value)) %>%
  mutate(units = 'Mg/ha') %>%
  ## Aggregating everything to FWD.
  pivot_wider(names_from = variable, values_from = value, 
              id_cols = c(study, treatment, years_post, forest_type, region, 
                          burn_season, thin_type, other)) %>%
  mutate(litterduff = case_when(is.na(litterduff) ~ litter + duff,
                         !is.na(litterduff) ~ 1 * litterduff))

gg_ld <- gg_fun(table = litter_duff_table, variable = litterduff) +
  ggtitle('Litter and duff') +
  ylab('Megagrams per hectare')
gg_ld

#save_graph(graph = gg_ld, name = 'litterduff')
```

```{r canopy bulk density}
cbd_table <- factored %>%
  filter(variable == 'canopy_bulk_density') %>%
  mutate(value = case_when(
    units == '100kg/m3' ~ value/100,
    units == 'kg/m3' ~ value))

gg_cbd <- gg_fun(table = cbd_table, variable = value) +
  ggtitle('Canopy bulk density') +
  ylab('Kilograms per meter cubed') +
  scale_y_continuous(limits = c(0,0.2), breaks = c(0,0.1,0.2))
gg_cbd

#save_graph(gg_cbd, 'cbd')
```

```{r canopy base height}
cbh_table <- factored %>%
  filter(variable == 'canopy_base_height')

gg_cbh <- gg_fun(table = cbh_table, variable = value) +
  ggtitle('Canopy base height') +
  ylab('Meters')
gg_cbh

#save_graph(gg_cbh, 'cbh')
```

```{r basal area}
ba_table <- factored %>%
  filter(variable == 'basal_area') %>%
  filter(value < 100)

gg_ba <- gg_fun(table = ba_table, variable = value) +
  ggtitle('Basal area') + 
  ylab('Meters squared per hectare')
gg_ba

#save_graph(gg_ba, 'basal_area')
```

```{r density}
den_table <- factored %>%
  filter(variable == 'density') 

gg_den <- gg_fun(table = den_table, variable = value) +
  ggtitle('Density') +
  ylab('Trees per hectare')
gg_den

#save_graph(gg_den, 'density')
```

```{r qmd}
qmd_table <- factored %>%
  filter(variable == 'qmd')

gg_qmd <- gg_fun(table = qmd_table, variable = value) +
  ggtitle('Quadratic mean diameter') +
  ylab('Centimeters')
gg_qmd

#save_graph(gg_qmd, 'qmd')
```